spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lid
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ""


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl