server:
  port: 8080
  servlet:
    context-path: /vg/v1
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      pool-name: MyHikariCP
      max-lifetime: 1800000
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sql:
    init:
      encoding: utf-8
      mode: always
      platform: postgresql
      schema-locations:
      - classpath:db/${spring.sql.init.platform}/schema-user.sql
      data-locations:
      - classpath:db/${spring.sql.init.platform}/data-user.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
      schema: public
      logic-delete-field: delete_time
      logic-delete-value: 'now()'
      logic-not-delete-value: 'null'
  type-aliases-package: com.vainglory.pojo